[package]
name = "sceleton"
version = "0.1.0"
authors = ["Christian Benincasa <chrisbenincasa@gmail.com>"]
edition = "2018"

[dependencies]
tempfile = "3.0.7"
clap = "2.32.0"
url = "1.7.2"
fs_extra = "1.1.0"
mustache = "0.9.0"
serde = "1.0.89"
